"""empty message

Revision ID: 145d84ee0de9
Revises: e81c0bda0044
Create Date: 2025-07-25 07:04:03.265441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145d84ee0de9'
down_revision = 'e81c0bda0044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learn_more', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learn_more', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
